export const SET_WEATHER_WIDGET_DATA = 'SET_WEATHER_WIDGET_DATA'
export const SET_WEATHER_WIDGET_TYPE = 'SET_WEATHER_WIDGET_TYPE'
export const SET_WEATHER_WIDGET_DATE = 'SET_WEATHER_WIDGET_DATE'
export const SET_WEATHER_WIDGET_VALIDATE = 'SET_WEATHER_WIDGET_VALIDATE'
